name: CI-CD-To-AWS
env: 
EB_PACKAGE_S3_BUCKET_NAME : "demopackage"
EB_APPLICATION_NAME : "API"
EB_ENVIRONMENT_NAME : "API-dev"
DEPLOY_PACKAGE_NAME : "api_app_${{github.sha}}.zip"
AWS_REGION_NAME : "eu-central-1"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:  
  ci-part:
      
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name : Create ZIP Deployment package
      run : zip -r ${{env.DEPLOY_PACKAGE_NAME}} ./ -x *.git*
   
   - name : Configure credentials
     uses : aws-actions/configure-aws-credentials@v1
     with:
        aws-access-key-id : ${{ secrets.MY_AWS_ACCESS_KEY }}
        aws-secret-access-key : ${{ secrets.MY_AWS_SECRET_KEY }}
        AWS-REGION : $ {{env.AWS_REGION_NAME }}
        
  - name : Copy Deployment package to S3 package
    run : aws s3 cp ${{env.DEPLOY_PACKAGE_NAME}} s3://${{env.EB_PACKAGE_S3_BUCKET_NAME}}/
    
  - name : Print Status Message for CI finish
    run : echo "CI Pipeline part Finished successfully"
    
cd-part: 
  runs-on: ubuntu-latest
  needs: [ci-part]
  
  steps: 
    - name : Configure credentials
     uses : aws-actions/configure-aws-credentials@v1
     with:
        aws-access-key-id : ${{ secrets.MY_AWS_ACCESS_KEY }}
        aws-secret-access-key : ${{ secrets.MY_AWS_SECRET_KEY }}
        AWS-REGION : $ {{env.AWS_REGION_NAME }}
        
    - name: Create new ElasticBeanstalk Application
      run : |
        aws elasticbeanstalk create-application-version \
        --application-name ${{env.EB_APPLICATION_NAME}}  \
        -- source-bundle S3Bucket="${{env.EB_PACKAGE_S3_BUCKET_NAME}}", S3Key="${{env.DEPLOY_PACKAGE_NAME}}" \
        -- version-label "Ver-${{github.sha}}" \
        -- description "CommitSHA-${{github.sha}}"
         
     - name: Deploy new ElasticBeansTalk Application Version
       run : aws elasticbeanstalk update-environment -- environment-name ${{env.EB_ENVIRONMENT_NAME}} --version-label "Ver-${{github.sha}}"
    
     - name : Print Status Message for CD finish
        run : echo "CD Pipeline part Finished successfully"
